<<<<<<< HEAD
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 018fea7542c0f03212b9cb4028f94dbd345342614de2504ed0976f0baadff3fbbe266691b8bc32063e4b3e0d8424c3c4e90345b77871d7e7398a78a1d7d0e281

test:
  secret_key_base: 5eb4615c99f591cd82fad9ee48b59ec87c45e8be9430a7ad653b6ca6987a6ee47a5ccc12e84e0e9fc3897e3639b86c5cc77d846788254cd7c10a1d610f8e8286

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
=======
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 018fea7542c0f03212b9cb4028f94dbd345342614de2504ed0976f0baadff3fbbe266691b8bc32063e4b3e0d8424c3c4e90345b77871d7e7398a78a1d7d0e281

test:
  secret_key_base: 5eb4615c99f591cd82fad9ee48b59ec87c45e8be9430a7ad653b6ca6987a6ee47a5ccc12e84e0e9fc3897e3639b86c5cc77d846788254cd7c10a1d610f8e8286

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
>>>>>>> 9dc1311096f73a30bbafec7f538b4eb90090fc98
